# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import finance_bo_pb2 as finance__bo__pb2


class FinanceBackOfficeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AutoIncomingCash = channel.unary_unary(
                '/packets.FinanceBackOffice/AutoIncomingCash',
                request_serializer=finance__bo__pb2.IncomingCashRequest.SerializeToString,
                response_deserializer=finance__bo__pb2.IncomingCashResponse.FromString,
                )
        self.GetInternalTransferByLoanID = channel.unary_unary(
                '/packets.FinanceBackOffice/GetInternalTransferByLoanID',
                request_serializer=finance__bo__pb2.InputGetInternalTransferByLoanID.SerializeToString,
                response_deserializer=finance__bo__pb2.OutputFinanceBackOffice.FromString,
                )
        self.UpdateInternalTransferStatus = channel.unary_unary(
                '/packets.FinanceBackOffice/UpdateInternalTransferStatus',
                request_serializer=finance__bo__pb2.InputUpdateInternalTransferStatus.SerializeToString,
                response_deserializer=finance__bo__pb2.OutputUpdateInternalTransferStatus.FromString,
                )
        self.GetBankList = channel.unary_unary(
                '/packets.FinanceBackOffice/GetBankList',
                request_serializer=finance__bo__pb2.InputGetBankList.SerializeToString,
                response_deserializer=finance__bo__pb2.OutputGetBankList.FromString,
                )
        self.KoinInvoiceDisbursementCallback = channel.unary_unary(
                '/packets.FinanceBackOffice/KoinInvoiceDisbursementCallback',
                request_serializer=finance__bo__pb2.KoinInvoiceDisbursementRequest.SerializeToString,
                response_deserializer=finance__bo__pb2.KoinInvoiceDisbursementResponse.FromString,
                )


class FinanceBackOfficeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AutoIncomingCash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInternalTransferByLoanID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInternalTransferStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBankList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KoinInvoiceDisbursementCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinanceBackOfficeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AutoIncomingCash': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoIncomingCash,
                    request_deserializer=finance__bo__pb2.IncomingCashRequest.FromString,
                    response_serializer=finance__bo__pb2.IncomingCashResponse.SerializeToString,
            ),
            'GetInternalTransferByLoanID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInternalTransferByLoanID,
                    request_deserializer=finance__bo__pb2.InputGetInternalTransferByLoanID.FromString,
                    response_serializer=finance__bo__pb2.OutputFinanceBackOffice.SerializeToString,
            ),
            'UpdateInternalTransferStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInternalTransferStatus,
                    request_deserializer=finance__bo__pb2.InputUpdateInternalTransferStatus.FromString,
                    response_serializer=finance__bo__pb2.OutputUpdateInternalTransferStatus.SerializeToString,
            ),
            'GetBankList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBankList,
                    request_deserializer=finance__bo__pb2.InputGetBankList.FromString,
                    response_serializer=finance__bo__pb2.OutputGetBankList.SerializeToString,
            ),
            'KoinInvoiceDisbursementCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.KoinInvoiceDisbursementCallback,
                    request_deserializer=finance__bo__pb2.KoinInvoiceDisbursementRequest.FromString,
                    response_serializer=finance__bo__pb2.KoinInvoiceDisbursementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.FinanceBackOffice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FinanceBackOffice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AutoIncomingCash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.FinanceBackOffice/AutoIncomingCash',
            finance__bo__pb2.IncomingCashRequest.SerializeToString,
            finance__bo__pb2.IncomingCashResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInternalTransferByLoanID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.FinanceBackOffice/GetInternalTransferByLoanID',
            finance__bo__pb2.InputGetInternalTransferByLoanID.SerializeToString,
            finance__bo__pb2.OutputFinanceBackOffice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateInternalTransferStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.FinanceBackOffice/UpdateInternalTransferStatus',
            finance__bo__pb2.InputUpdateInternalTransferStatus.SerializeToString,
            finance__bo__pb2.OutputUpdateInternalTransferStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBankList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.FinanceBackOffice/GetBankList',
            finance__bo__pb2.InputGetBankList.SerializeToString,
            finance__bo__pb2.OutputGetBankList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def KoinInvoiceDisbursementCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.FinanceBackOffice/KoinInvoiceDisbursementCallback',
            finance__bo__pb2.KoinInvoiceDisbursementRequest.SerializeToString,
            finance__bo__pb2.KoinInvoiceDisbursementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
