# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koinemployee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12koinemployee.proto\x12\x07packets\x1a\x19google/protobuf/any.proto\"-\n\x1bInputKoinEmployeeDetailLoan\x12\x0e\n\x06LoanID\x18\x01 \x01(\x03\"4\n\"InputKoinEmployeeVendorInformation\x12\x0e\n\x06LoanID\x18\x01 \x01(\x03\"N\n\x1cOutputKoinEmployeeDetailLoan\x12.\n\x05\x44\x61tas\x18\x01 \x03(\x0b\x32\x1f.packets.KoinEmployeeDetailLoan\"\x83\x02\n\x16KoinEmployeeDetailLoan\x12\x15\n\rLoanDetailsID\x18\x01 \x01(\x03\x12\x0e\n\x06LoanID\x18\x02 \x01(\x03\x12\x13\n\x0b\x44\x65tailGroup\x18\x03 \x01(\t\x12\x12\n\nDetailName\x18\x04 \x01(\t\x12\x13\n\x0b\x44\x65tailValue\x18\x05 \x01(\t\x12\x10\n\x08IsActive\x18\x06 \x01(\x03\x12\x11\n\tCreatedBy\x18\x07 \x01(\t\x12\x11\n\tCreatedAt\x18\x08 \x01(\t\x12\x12\n\nModifiedBy\x18\t \x01(\t\x12\x12\n\nModifiedAt\x18\n \x01(\t\x12\x11\n\tDeletedBy\x18\x0b \x01(\t\x12\x11\n\tDeletedAt\x18\x0c \x01(\t\"S\n\x1dKoinEmployeeVendorInformation\x12\x0e\n\x06Status\x18\x01 \x01(\x05\x12\"\n\x04\x44\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"i\n\"OutputLoanInformationKoinEmployees\x12\x0e\n\x06Status\x18\x01 \x01(\x05\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\"\n\x04\x44\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any2\xc3\x02\n\rKoinEmployees\x12[\n\nDetailLoan\x12$.packets.InputKoinEmployeeDetailLoan\x1a%.packets.OutputKoinEmployeeDetailLoan\"\x00\x12j\n\x11VendorInformation\x12+.packets.InputKoinEmployeeVendorInformation\x1a&.packets.KoinEmployeeVendorInformation\"\x00\x12i\n\x12GetLoanInformation\x12$.packets.InputKoinEmployeeDetailLoan\x1a+.packets.OutputLoanInformationKoinEmployees\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'koinemployee_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTKOINEMPLOYEEDETAILLOAN']._serialized_start=58
  _globals['_INPUTKOINEMPLOYEEDETAILLOAN']._serialized_end=103
  _globals['_INPUTKOINEMPLOYEEVENDORINFORMATION']._serialized_start=105
  _globals['_INPUTKOINEMPLOYEEVENDORINFORMATION']._serialized_end=157
  _globals['_OUTPUTKOINEMPLOYEEDETAILLOAN']._serialized_start=159
  _globals['_OUTPUTKOINEMPLOYEEDETAILLOAN']._serialized_end=237
  _globals['_KOINEMPLOYEEDETAILLOAN']._serialized_start=240
  _globals['_KOINEMPLOYEEDETAILLOAN']._serialized_end=499
  _globals['_KOINEMPLOYEEVENDORINFORMATION']._serialized_start=501
  _globals['_KOINEMPLOYEEVENDORINFORMATION']._serialized_end=584
  _globals['_OUTPUTLOANINFORMATIONKOINEMPLOYEES']._serialized_start=586
  _globals['_OUTPUTLOANINFORMATIONKOINEMPLOYEES']._serialized_end=691
  _globals['_KOINEMPLOYEES']._serialized_start=694
  _globals['_KOINEMPLOYEES']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
