# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import koingold_pb2 as koingold__pb2


class KoinGoldStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransactionDetail = channel.unary_unary(
                '/packets.KoinGold/TransactionDetail',
                request_serializer=koingold__pb2.InputKoinGoldTransactionDetail.SerializeToString,
                response_deserializer=koingold__pb2.OutputKoinGoldTransactionDetail.FromString,
                )
        self.AddUserGold = channel.unary_unary(
                '/packets.KoinGold/AddUserGold',
                request_serializer=koingold__pb2.InputAddUserGold.SerializeToString,
                response_deserializer=koingold__pb2.OutputAddUserGold.FromString,
                )
        self.GetOrderHistoryDetailByTransactionId = channel.unary_unary(
                '/packets.KoinGold/GetOrderHistoryDetailByTransactionId',
                request_serializer=koingold__pb2.InputOrderHistoryDetail.SerializeToString,
                response_deserializer=koingold__pb2.OutputOrderHistoryDetail.FromString,
                )
        self.GetGoldTaxCalculation = channel.unary_unary(
                '/packets.KoinGold/GetGoldTaxCalculation',
                request_serializer=koingold__pb2.InputGetGoldTaxCalculation.SerializeToString,
                response_deserializer=koingold__pb2.OutputGetGoldTaxCalculation.FromString,
                )
        self.GetInOutCashGoldData = channel.unary_unary(
                '/packets.KoinGold/GetInOutCashGoldData',
                request_serializer=koingold__pb2.InputGetInOutCashGoldData.SerializeToString,
                response_deserializer=koingold__pb2.OutputGetInOutCashGoldData.FromString,
                )
        self.GetUserGoldPortfolioDetails = channel.unary_unary(
                '/packets.KoinGold/GetUserGoldPortfolioDetails',
                request_serializer=koingold__pb2.InputGetUserGoldPortfolioDetails.SerializeToString,
                response_deserializer=koingold__pb2.OutputGetUserGoldPortfolioDetails.FromString,
                )
        self.GetUserCurrentGoldDetails = channel.unary_unary(
                '/packets.KoinGold/GetUserCurrentGoldDetails',
                request_serializer=koingold__pb2.InputUserId.SerializeToString,
                response_deserializer=koingold__pb2.OutputUserCurrentGoldDetails.FromString,
                )
        self.GetDistinctActiveUserIds = channel.unary_unary(
                '/packets.KoinGold/GetDistinctActiveUserIds',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=koingold__pb2.OutputUserIds.FromString,
                )


class KoinGoldServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransactionDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserGold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderHistoryDetailByTransactionId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoldTaxCalculation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInOutCashGoldData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserGoldPortfolioDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserCurrentGoldDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistinctActiveUserIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KoinGoldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransactionDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionDetail,
                    request_deserializer=koingold__pb2.InputKoinGoldTransactionDetail.FromString,
                    response_serializer=koingold__pb2.OutputKoinGoldTransactionDetail.SerializeToString,
            ),
            'AddUserGold': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserGold,
                    request_deserializer=koingold__pb2.InputAddUserGold.FromString,
                    response_serializer=koingold__pb2.OutputAddUserGold.SerializeToString,
            ),
            'GetOrderHistoryDetailByTransactionId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderHistoryDetailByTransactionId,
                    request_deserializer=koingold__pb2.InputOrderHistoryDetail.FromString,
                    response_serializer=koingold__pb2.OutputOrderHistoryDetail.SerializeToString,
            ),
            'GetGoldTaxCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoldTaxCalculation,
                    request_deserializer=koingold__pb2.InputGetGoldTaxCalculation.FromString,
                    response_serializer=koingold__pb2.OutputGetGoldTaxCalculation.SerializeToString,
            ),
            'GetInOutCashGoldData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInOutCashGoldData,
                    request_deserializer=koingold__pb2.InputGetInOutCashGoldData.FromString,
                    response_serializer=koingold__pb2.OutputGetInOutCashGoldData.SerializeToString,
            ),
            'GetUserGoldPortfolioDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserGoldPortfolioDetails,
                    request_deserializer=koingold__pb2.InputGetUserGoldPortfolioDetails.FromString,
                    response_serializer=koingold__pb2.OutputGetUserGoldPortfolioDetails.SerializeToString,
            ),
            'GetUserCurrentGoldDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserCurrentGoldDetails,
                    request_deserializer=koingold__pb2.InputUserId.FromString,
                    response_serializer=koingold__pb2.OutputUserCurrentGoldDetails.SerializeToString,
            ),
            'GetDistinctActiveUserIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistinctActiveUserIds,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=koingold__pb2.OutputUserIds.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.KoinGold', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KoinGold(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransactionDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/TransactionDetail',
            koingold__pb2.InputKoinGoldTransactionDetail.SerializeToString,
            koingold__pb2.OutputKoinGoldTransactionDetail.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserGold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/AddUserGold',
            koingold__pb2.InputAddUserGold.SerializeToString,
            koingold__pb2.OutputAddUserGold.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderHistoryDetailByTransactionId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/GetOrderHistoryDetailByTransactionId',
            koingold__pb2.InputOrderHistoryDetail.SerializeToString,
            koingold__pb2.OutputOrderHistoryDetail.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGoldTaxCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/GetGoldTaxCalculation',
            koingold__pb2.InputGetGoldTaxCalculation.SerializeToString,
            koingold__pb2.OutputGetGoldTaxCalculation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInOutCashGoldData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/GetInOutCashGoldData',
            koingold__pb2.InputGetInOutCashGoldData.SerializeToString,
            koingold__pb2.OutputGetInOutCashGoldData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserGoldPortfolioDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/GetUserGoldPortfolioDetails',
            koingold__pb2.InputGetUserGoldPortfolioDetails.SerializeToString,
            koingold__pb2.OutputGetUserGoldPortfolioDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserCurrentGoldDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/GetUserCurrentGoldDetails',
            koingold__pb2.InputUserId.SerializeToString,
            koingold__pb2.OutputUserCurrentGoldDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDistinctActiveUserIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.KoinGold/GetDistinctActiveUserIds',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            koingold__pb2.OutputUserIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
