# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import midgardbackoffice_pb2 as midgardbackoffice__pb2


class MidgardBackofficeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLoanDetailCollection = channel.unary_stream(
                '/packets.MidgardBackoffice/GetLoanDetailCollection',
                request_serializer=midgardbackoffice__pb2.GetLoanDetailCollectionRequest.SerializeToString,
                response_deserializer=midgardbackoffice__pb2.LoanDetailCollection.FromString,
                )


class MidgardBackofficeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLoanDetailCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MidgardBackofficeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLoanDetailCollection': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLoanDetailCollection,
                    request_deserializer=midgardbackoffice__pb2.GetLoanDetailCollectionRequest.FromString,
                    response_serializer=midgardbackoffice__pb2.LoanDetailCollection.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.MidgardBackoffice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MidgardBackoffice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLoanDetailCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/packets.MidgardBackoffice/GetLoanDetailCollection',
            midgardbackoffice__pb2.GetLoanDetailCollectionRequest.SerializeToString,
            midgardbackoffice__pb2.LoanDetailCollection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
