# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: midgardbackoffice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17midgardbackoffice.proto\x12\x07packets\"\xd0\x02\n\x14LoanDetailCollection\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\x10\n\x08UserCode\x18\x02 \x01(\t\x12\x11\n\tAgentType\x18\x03 \x01(\t\x12\x0f\n\x07\x41gentID\x18\x04 \x01(\t\x12\x12\n\nAgentEmail\x18\x05 \x01(\t\x12\x1b\n\x13\x41gentAllocationTime\x18\x06 \x01(\t\x12\x12\n\nActionDate\x18\x07 \x01(\t\x12\x12\n\nActionTime\x18\x08 \x01(\t\x12\x12\n\nActionMode\x18\t \x01(\t\x12\x16\n\x0e\x41\x63tionLocation\x18\n \x01(\t\x12\x17\n\x0fPersonContacted\x18\x0b \x01(\t\x12\x12\n\nActionCode\x18\x0c \x01(\t\x12\x12\n\nNextAction\x18\r \x01(\t\x12\x0f\n\x07PTPDate\x18\x0e \x01(\t\x12\x11\n\tPTPAmount\x18\x0f \x01(\x01\x12\x0c\n\x04Note\x18\x10 \x01(\t\"H\n\x1eGetLoanDetailCollectionRequest\x12\x10\n\x08LoanCode\x18\x01 \x01(\t\x12\x14\n\x0cInsertedDate\x18\x02 \x01(\t2z\n\x11MidgardBackoffice\x12\x65\n\x17GetLoanDetailCollection\x12\'.packets.GetLoanDetailCollectionRequest\x1a\x1d.packets.LoanDetailCollection\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'midgardbackoffice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOANDETAILCOLLECTION']._serialized_start=37
  _globals['_LOANDETAILCOLLECTION']._serialized_end=373
  _globals['_GETLOANDETAILCOLLECTIONREQUEST']._serialized_start=375
  _globals['_GETLOANDETAILCOLLECTIONREQUEST']._serialized_end=447
  _globals['_MIDGARDBACKOFFICE']._serialized_start=449
  _globals['_MIDGARDBACKOFFICE']._serialized_end=571
# @@protoc_insertion_point(module_scope)
