# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import notifications_pb2 as notifications__pb2


class NotificationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEmail = channel.unary_unary(
                '/packets.Notifications/SendEmail',
                request_serializer=notifications__pb2.InSendEmail.SerializeToString,
                response_deserializer=notifications__pb2.OutSend.FromString,
                )
        self.SendMobilePush = channel.unary_unary(
                '/packets.Notifications/SendMobilePush',
                request_serializer=notifications__pb2.InSendMobilePush.SerializeToString,
                response_deserializer=notifications__pb2.OutSend.FromString,
                )
        self.SendWhatsApp = channel.unary_unary(
                '/packets.Notifications/SendWhatsApp',
                request_serializer=notifications__pb2.InSendWhatsapp.SerializeToString,
                response_deserializer=notifications__pb2.OutSend.FromString,
                )
        self.SendSMS = channel.unary_unary(
                '/packets.Notifications/SendSMS',
                request_serializer=notifications__pb2.InSendSMS.SerializeToString,
                response_deserializer=notifications__pb2.OutSend.FromString,
                )
        self.SendInApp = channel.unary_unary(
                '/packets.Notifications/SendInApp',
                request_serializer=notifications__pb2.InSendInApp.SerializeToString,
                response_deserializer=notifications__pb2.OutSend.FromString,
                )
        self.Send = channel.unary_unary(
                '/packets.Notifications/Send',
                request_serializer=notifications__pb2.InSend.SerializeToString,
                response_deserializer=notifications__pb2.OutSend.FromString,
                )
        self.CreateUserDevice = channel.unary_unary(
                '/packets.Notifications/CreateUserDevice',
                request_serializer=notifications__pb2.InUserDevice.SerializeToString,
                response_deserializer=notifications__pb2.OutUserDevice.FromString,
                )


class NotificationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMobilePush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWhatsApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSMS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=notifications__pb2.InSendEmail.FromString,
                    response_serializer=notifications__pb2.OutSend.SerializeToString,
            ),
            'SendMobilePush': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMobilePush,
                    request_deserializer=notifications__pb2.InSendMobilePush.FromString,
                    response_serializer=notifications__pb2.OutSend.SerializeToString,
            ),
            'SendWhatsApp': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWhatsApp,
                    request_deserializer=notifications__pb2.InSendWhatsapp.FromString,
                    response_serializer=notifications__pb2.OutSend.SerializeToString,
            ),
            'SendSMS': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSMS,
                    request_deserializer=notifications__pb2.InSendSMS.FromString,
                    response_serializer=notifications__pb2.OutSend.SerializeToString,
            ),
            'SendInApp': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInApp,
                    request_deserializer=notifications__pb2.InSendInApp.FromString,
                    response_serializer=notifications__pb2.OutSend.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=notifications__pb2.InSend.FromString,
                    response_serializer=notifications__pb2.OutSend.SerializeToString,
            ),
            'CreateUserDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserDevice,
                    request_deserializer=notifications__pb2.InUserDevice.FromString,
                    response_serializer=notifications__pb2.OutUserDevice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.Notifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notifications(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/SendEmail',
            notifications__pb2.InSendEmail.SerializeToString,
            notifications__pb2.OutSend.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMobilePush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/SendMobilePush',
            notifications__pb2.InSendMobilePush.SerializeToString,
            notifications__pb2.OutSend.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendWhatsApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/SendWhatsApp',
            notifications__pb2.InSendWhatsapp.SerializeToString,
            notifications__pb2.OutSend.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendSMS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/SendSMS',
            notifications__pb2.InSendSMS.SerializeToString,
            notifications__pb2.OutSend.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendInApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/SendInApp',
            notifications__pb2.InSendInApp.SerializeToString,
            notifications__pb2.OutSend.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/Send',
            notifications__pb2.InSend.SerializeToString,
            notifications__pb2.OutSend.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUserDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Notifications/CreateUserDevice',
            notifications__pb2.InUserDevice.SerializeToString,
            notifications__pb2.OutUserDevice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
