# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import productsportfolio_pb2 as productsportfolio__pb2


class ProductsPortfolioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePortfolioPostDisbursement = channel.unary_unary(
                '/packets.ProductsPortfolio/UpdatePortfolioPostDisbursement',
                request_serializer=productsportfolio__pb2.LenderRepaymentSchedulesSummary.SerializeToString,
                response_deserializer=productsportfolio__pb2.UpdatePortfolioPostDisbursementResp.FromString,
                )
        self.CreateOrUpdatePortfolioPostSuccessfulPurchase = channel.unary_unary(
                '/packets.ProductsPortfolio/CreateOrUpdatePortfolioPostSuccessfulPurchase',
                request_serializer=productsportfolio__pb2.PurchaseSuccessfulSummary.SerializeToString,
                response_deserializer=productsportfolio__pb2.CreateOrUpdatePortfolioPostStatus.FromString,
                )
        self.UpdatePortfolioWhenLenderOrderCancelled = channel.unary_unary(
                '/packets.ProductsPortfolio/UpdatePortfolioWhenLenderOrderCancelled',
                request_serializer=productsportfolio__pb2.LenderOrderCancelledDetails.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioUpdateResp.FromString,
                )
        self.UpdatePortfolioWhenLoanCancelledByBorrower = channel.unary_unary(
                '/packets.ProductsPortfolio/UpdatePortfolioWhenLoanCancelledByBorrower',
                request_serializer=productsportfolio__pb2.LoanCancelledByBorrowerDetails.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioUpdateResp.FromString,
                )
        self.UpdatePortfolioWhenLoanBecomesNPL = channel.unary_unary(
                '/packets.ProductsPortfolio/UpdatePortfolioWhenLoanBecomesNPL',
                request_serializer=productsportfolio__pb2.NLPLoanDetails.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioUpdateResp.FromString,
                )
        self.UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully = channel.unary_unary(
                '/packets.ProductsPortfolio/UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully',
                request_serializer=productsportfolio__pb2.ProvisionFundSpreadingDetails.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioUpdateResp.FromString,
                )
        self.CreateOrUpdatePortfolioPostRoboPurchaseSuccessful = channel.unary_unary(
                '/packets.ProductsPortfolio/CreateOrUpdatePortfolioPostRoboPurchaseSuccessful',
                request_serializer=productsportfolio__pb2.RoboPurchaseSuccessfulDetails.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioUpdateResp.FromString,
                )
        self.GetPortfolioForUserAndLoanCode = channel.unary_unary(
                '/packets.ProductsPortfolio/GetPortfolioForUserAndLoanCode',
                request_serializer=productsportfolio__pb2.PortfolioLoanDetails.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioDetailsResp.FromString,
                )
        self.GetExistencePortfolioUsers = channel.unary_unary(
                '/packets.ProductsPortfolio/GetExistencePortfolioUsers',
                request_serializer=productsportfolio__pb2.ExistencePortfolioUsersParams.SerializeToString,
                response_deserializer=productsportfolio__pb2.ExistencePortfolioUsersResp.FromString,
                )
        self.GetPortfolioAccountValueForUser = channel.unary_unary(
                '/packets.ProductsPortfolio/GetPortfolioAccountValueForUser',
                request_serializer=productsportfolio__pb2.PortfolioAccountValueInputParam.SerializeToString,
                response_deserializer=productsportfolio__pb2.PortfolioAccountValueDetails.FromString,
                )


class ProductsPortfolioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdatePortfolioPostDisbursement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrUpdatePortfolioPostSuccessfulPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePortfolioWhenLenderOrderCancelled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePortfolioWhenLoanCancelledByBorrower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePortfolioWhenLoanBecomesNPL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrUpdatePortfolioPostRoboPurchaseSuccessful(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolioForUserAndLoanCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExistencePortfolioUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolioAccountValueForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductsPortfolioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePortfolioPostDisbursement': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortfolioPostDisbursement,
                    request_deserializer=productsportfolio__pb2.LenderRepaymentSchedulesSummary.FromString,
                    response_serializer=productsportfolio__pb2.UpdatePortfolioPostDisbursementResp.SerializeToString,
            ),
            'CreateOrUpdatePortfolioPostSuccessfulPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdatePortfolioPostSuccessfulPurchase,
                    request_deserializer=productsportfolio__pb2.PurchaseSuccessfulSummary.FromString,
                    response_serializer=productsportfolio__pb2.CreateOrUpdatePortfolioPostStatus.SerializeToString,
            ),
            'UpdatePortfolioWhenLenderOrderCancelled': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortfolioWhenLenderOrderCancelled,
                    request_deserializer=productsportfolio__pb2.LenderOrderCancelledDetails.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioUpdateResp.SerializeToString,
            ),
            'UpdatePortfolioWhenLoanCancelledByBorrower': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortfolioWhenLoanCancelledByBorrower,
                    request_deserializer=productsportfolio__pb2.LoanCancelledByBorrowerDetails.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioUpdateResp.SerializeToString,
            ),
            'UpdatePortfolioWhenLoanBecomesNPL': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortfolioWhenLoanBecomesNPL,
                    request_deserializer=productsportfolio__pb2.NLPLoanDetails.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioUpdateResp.SerializeToString,
            ),
            'UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully,
                    request_deserializer=productsportfolio__pb2.ProvisionFundSpreadingDetails.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioUpdateResp.SerializeToString,
            ),
            'CreateOrUpdatePortfolioPostRoboPurchaseSuccessful': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdatePortfolioPostRoboPurchaseSuccessful,
                    request_deserializer=productsportfolio__pb2.RoboPurchaseSuccessfulDetails.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioUpdateResp.SerializeToString,
            ),
            'GetPortfolioForUserAndLoanCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolioForUserAndLoanCode,
                    request_deserializer=productsportfolio__pb2.PortfolioLoanDetails.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioDetailsResp.SerializeToString,
            ),
            'GetExistencePortfolioUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExistencePortfolioUsers,
                    request_deserializer=productsportfolio__pb2.ExistencePortfolioUsersParams.FromString,
                    response_serializer=productsportfolio__pb2.ExistencePortfolioUsersResp.SerializeToString,
            ),
            'GetPortfolioAccountValueForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolioAccountValueForUser,
                    request_deserializer=productsportfolio__pb2.PortfolioAccountValueInputParam.FromString,
                    response_serializer=productsportfolio__pb2.PortfolioAccountValueDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.ProductsPortfolio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductsPortfolio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdatePortfolioPostDisbursement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/UpdatePortfolioPostDisbursement',
            productsportfolio__pb2.LenderRepaymentSchedulesSummary.SerializeToString,
            productsportfolio__pb2.UpdatePortfolioPostDisbursementResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrUpdatePortfolioPostSuccessfulPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/CreateOrUpdatePortfolioPostSuccessfulPurchase',
            productsportfolio__pb2.PurchaseSuccessfulSummary.SerializeToString,
            productsportfolio__pb2.CreateOrUpdatePortfolioPostStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePortfolioWhenLenderOrderCancelled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/UpdatePortfolioWhenLenderOrderCancelled',
            productsportfolio__pb2.LenderOrderCancelledDetails.SerializeToString,
            productsportfolio__pb2.PortfolioUpdateResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePortfolioWhenLoanCancelledByBorrower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/UpdatePortfolioWhenLoanCancelledByBorrower',
            productsportfolio__pb2.LoanCancelledByBorrowerDetails.SerializeToString,
            productsportfolio__pb2.PortfolioUpdateResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePortfolioWhenLoanBecomesNPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/UpdatePortfolioWhenLoanBecomesNPL',
            productsportfolio__pb2.NLPLoanDetails.SerializeToString,
            productsportfolio__pb2.PortfolioUpdateResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/UpdatePortfolioWhenProvisionFundSpreadToLenderSuccessfully',
            productsportfolio__pb2.ProvisionFundSpreadingDetails.SerializeToString,
            productsportfolio__pb2.PortfolioUpdateResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrUpdatePortfolioPostRoboPurchaseSuccessful(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/CreateOrUpdatePortfolioPostRoboPurchaseSuccessful',
            productsportfolio__pb2.RoboPurchaseSuccessfulDetails.SerializeToString,
            productsportfolio__pb2.PortfolioUpdateResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPortfolioForUserAndLoanCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/GetPortfolioForUserAndLoanCode',
            productsportfolio__pb2.PortfolioLoanDetails.SerializeToString,
            productsportfolio__pb2.PortfolioDetailsResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExistencePortfolioUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/GetExistencePortfolioUsers',
            productsportfolio__pb2.ExistencePortfolioUsersParams.SerializeToString,
            productsportfolio__pb2.ExistencePortfolioUsersResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPortfolioAccountValueForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.ProductsPortfolio/GetPortfolioAccountValueForUser',
            productsportfolio__pb2.PortfolioAccountValueInputParam.SerializeToString,
            productsportfolio__pb2.PortfolioAccountValueDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
