# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import superapp_pb2 as superapp__pb2


class SuperappStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItemToggleByMobile = channel.unary_unary(
                '/packets.Superapp/GetItemToggleByMobile',
                request_serializer=superapp__pb2.ParamGetItemToggleByMobile.SerializeToString,
                response_deserializer=superapp__pb2.OutputItemToggleByMobile.FromString,
                )
        self.GetItemToggle = channel.unary_unary(
                '/packets.Superapp/GetItemToggle',
                request_serializer=superapp__pb2.ParamGetItemToggle.SerializeToString,
                response_deserializer=superapp__pb2.OutputItemToggle.FromString,
                )
        self.GetItemToggleByID = channel.unary_unary(
                '/packets.Superapp/GetItemToggleByID',
                request_serializer=superapp__pb2.ParamGetItemToggleByID.SerializeToString,
                response_deserializer=superapp__pb2.OutputItemToggleByID.FromString,
                )


class SuperappServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItemToggleByMobile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemToggle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemToggleByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperappServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItemToggleByMobile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemToggleByMobile,
                    request_deserializer=superapp__pb2.ParamGetItemToggleByMobile.FromString,
                    response_serializer=superapp__pb2.OutputItemToggleByMobile.SerializeToString,
            ),
            'GetItemToggle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemToggle,
                    request_deserializer=superapp__pb2.ParamGetItemToggle.FromString,
                    response_serializer=superapp__pb2.OutputItemToggle.SerializeToString,
            ),
            'GetItemToggleByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemToggleByID,
                    request_deserializer=superapp__pb2.ParamGetItemToggleByID.FromString,
                    response_serializer=superapp__pb2.OutputItemToggleByID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.Superapp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Superapp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItemToggleByMobile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Superapp/GetItemToggleByMobile',
            superapp__pb2.ParamGetItemToggleByMobile.SerializeToString,
            superapp__pb2.OutputItemToggleByMobile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemToggle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Superapp/GetItemToggle',
            superapp__pb2.ParamGetItemToggle.SerializeToString,
            superapp__pb2.OutputItemToggle.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemToggleByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.Superapp/GetItemToggleByID',
            superapp__pb2.ParamGetItemToggleByID.SerializeToString,
            superapp__pb2.OutputItemToggleByID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
