# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ucl_pb2 as ucl__pb2


class UCLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InstantApproval = channel.unary_unary(
                '/packets.UCL/InstantApproval',
                request_serializer=ucl__pb2.InstantApprovalRequest.SerializeToString,
                response_deserializer=ucl__pb2.InstantApprovalResult.FromString,
                )
        self.GetFinishedUclHistory = channel.unary_unary(
                '/packets.UCL/GetFinishedUclHistory',
                request_serializer=ucl__pb2.GetFinishedUclHistoryRequest.SerializeToString,
                response_deserializer=ucl__pb2.GetFinishedUclHistoryResult.FromString,
                )
        self.GetSingleUclHistory = channel.unary_unary(
                '/packets.UCL/GetSingleUclHistory',
                request_serializer=ucl__pb2.GetSingleUclHistoryRequest.SerializeToString,
                response_deserializer=ucl__pb2.GetSingleUclHistoryResult.FromString,
                )
        self.SaveUserResponse = channel.unary_unary(
                '/packets.UCL/SaveUserResponse',
                request_serializer=ucl__pb2.SaveUserResponseRequest.SerializeToString,
                response_deserializer=ucl__pb2.SaveUserResponseResult.FromString,
                )


class UCLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InstantApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFinishedUclHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleUclHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveUserResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UCLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InstantApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.InstantApproval,
                    request_deserializer=ucl__pb2.InstantApprovalRequest.FromString,
                    response_serializer=ucl__pb2.InstantApprovalResult.SerializeToString,
            ),
            'GetFinishedUclHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinishedUclHistory,
                    request_deserializer=ucl__pb2.GetFinishedUclHistoryRequest.FromString,
                    response_serializer=ucl__pb2.GetFinishedUclHistoryResult.SerializeToString,
            ),
            'GetSingleUclHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleUclHistory,
                    request_deserializer=ucl__pb2.GetSingleUclHistoryRequest.FromString,
                    response_serializer=ucl__pb2.GetSingleUclHistoryResult.SerializeToString,
            ),
            'SaveUserResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveUserResponse,
                    request_deserializer=ucl__pb2.SaveUserResponseRequest.FromString,
                    response_serializer=ucl__pb2.SaveUserResponseResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packets.UCL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UCL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InstantApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.UCL/InstantApproval',
            ucl__pb2.InstantApprovalRequest.SerializeToString,
            ucl__pb2.InstantApprovalResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFinishedUclHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.UCL/GetFinishedUclHistory',
            ucl__pb2.GetFinishedUclHistoryRequest.SerializeToString,
            ucl__pb2.GetFinishedUclHistoryResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSingleUclHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.UCL/GetSingleUclHistory',
            ucl__pb2.GetSingleUclHistoryRequest.SerializeToString,
            ucl__pb2.GetSingleUclHistoryResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveUserResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/packets.UCL/SaveUserResponse',
            ucl__pb2.SaveUserResponseRequest.SerializeToString,
            ucl__pb2.SaveUserResponseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
